### PR TITLE
Make loading indicator edible to match the rest of the styling

### PR DESCRIPTION
**Pull request by easrng**
This was tested on master but was really made to match the styling on 1.3.0, which IMO looks better.

### CODE REVIEW

**Comment by jameslittle230** [comment]
Thanks for contributing!

The upcoming 1.4.0 release reworks a lot of the styling. Could you attach to this PR a screenshot of the the UI patched on top of master?

Thanks!
James

**Comment by easrng** [comment]
On master now:  
image

On master with change:  
image

On 1.3.0 now:  
image

On 1.3.0 with change:  
image

**Comment by jameslittle230** [comment]
Oooh - I like that a lot!! That's awesome!

I think it might be slightly _too_ lickable for the current default theme, but I'd love to merge this in as a new theme. Would you be willing to break it out into a different CSS file? (Naming is up to you!) I'm happy to make sure it gets built along with the rest of 1.4.0 and makes it onto https://stork-search.net/themes.

If you're amenable to that, would you want attribution on the Stork site? If so, with what name and/or URL should I credit you?

-James

**Comment by easrng** [comment]
How about I just add it on the 1.3.0 theme as a new theme?

**Comment by jameslittle230** [comment]
Say more? I think we're describing the same thing -- the list of themes would become "basic," "dark," "flat," and your theme.  Each theme is a different CSS file in the `themes/` directory.

**Comment by easrng** [comment]
Right yeah sorry I wasn't clear. I was just trying to ask if the one to add as a theme should be this one:  
image

**Comment by jameslittle230** [comment]
Ah, yeah, I see - the bigger gradients fit more with your loading bar.

Yeah, if you want to fork the 1.3.0 basic theme to build on top of edible.css I think that would look best

(And again, this looks awesome!)

**Comment by easrng** [comment]
ok there's probably redundant rules in edible/edible-dark.css but it should work now

**Comment by easrng** [comment]
wait just a sec

**Comment by easrng** [comment]
ok now i think it's good (i forgot to add @imports which i assume are needed since flat and dark have them

**Comment by jameslittle230** [comment]
I'll check about the imports and merge this once I've tested it locally!

Any thoughts on attribution on stork-search.net, or nah?

**Comment by easrng** [comment]
> Any thoughts on attribution on stork-search.net
I'm fine either way

**Comment by jameslittle230** [comment]
Closing this for #235, which integrates the theme with the project's deploy infrastructure and flattens the theme dependency tree!

**Pull request closed without merging**
